pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('Build'){
            steps{
                sh 'mvn clean package'
            }
            post{
                success{
                    echo "Archiving the Arctifacts"
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
        stage('Deploye to tomcat server')
        steps{
            deploy adapters: [tomcat9(path: '', url: 'http://localhost:8989/')], contextPath: null, war: '**/*.war'
        }
    }
}
